"use client";

import { Handshake, MapPinned, ShieldCheck, Warehouse } from "lucide-react";
import { useLanguage } from "@/components/language-provider";

const text = {
  fr: { eyebrow:"Né en Guinée-Bissau", title:"Les bons espaces font grandir", accent:"les bonnes idées.", intro:"AgroStock rapproche les entreprises, commerçants et producteurs des propriétaires d’espaces de stockage à travers le pays.", reason:"Notre raison d’être", reasonTitle:"Rendre visible ce qui existe déjà.", reasonText:"De nombreux entrepôts, hangars et magasins sont disponibles, mais restent difficiles à trouver. AgroStock les rassemble dans un annuaire simple, local et accessible sur téléphone.", quote:"Moins d’intermédiaires.\nPlus de contacts directs.", guide:"Ce qui nous guide", guideTitle:"Une plateforme pensée ici.", local:"Local", localText:"Des villes, quartiers et usages adaptés aux réalités de la Guinée-Bissau.", direct:"Direct", directText:"Un appel ou un message WhatsApp suffit pour joindre le propriétaire.", clear:"Clair", clearText:"Les informations essentielles réunies avant d’organiser une visite.", useful:"Utile", usefulText:"Tous les types d’espaces de stockage dans un annuaire unique." },
  pt: { eyebrow:"Nascido na Guiné-Bissau", title:"Os bons espaços fazem crescer", accent:"as boas ideias.", intro:"A AgroStock aproxima empresas, comerciantes e produtores dos proprietários de espaços de armazenamento em todo o país.", reason:"A nossa razão de ser", reasonTitle:"Dar visibilidade ao que já existe.", reasonText:"Muitos armazéns, hangares e lojas estão disponíveis, mas são difíceis de encontrar. A AgroStock reúne-os num diretório simples, local e acessível no telemóvel.", quote:"Menos intermediários.\nMais contactos diretos.", guide:"O que nos orienta", guideTitle:"Uma plataforma pensada aqui.", local:"Local", localText:"Cidades, bairros e usos adaptados à realidade da Guiné-Bissau.", direct:"Direto", directText:"Uma chamada ou mensagem WhatsApp liga-o diretamente ao proprietário.", clear:"Claro", clearText:"As informações essenciais reunidas antes de marcar uma visita.", useful:"Útil", usefulText:"Todos os tipos de espaços de armazenamento num único diretório." },
  en: { eyebrow:"Born in Guinea-Bissau", title:"The right spaces help grow", accent:"the right ideas.", intro:"AgroStock connects businesses, traders and producers with storage space owners across the country.", reason:"Why we exist", reasonTitle:"Make what already exists easier to find.", reasonText:"Many warehouses, hangars and stores are available but hard to discover. AgroStock brings them together in a simple, local directory built for phones.", quote:"Fewer middlemen.\nMore direct contacts.", guide:"What guides us", guideTitle:"A platform designed here.", local:"Local", localText:"Cities, neighborhoods and uses shaped around Guinea-Bissau realities.", direct:"Direct", directText:"A call or WhatsApp message connects you straight to the owner.", clear:"Clear", clearText:"The essential information gathered before arranging a visit.", useful:"Useful", usefulText:"Every type of storage space in one directory." }
} as const;

export default function AboutPage(){const{lang}=useLanguage();const t=text[lang];const values=[[MapPinned,t.local,t.localText],[Handshake,t.direct,t.directText],[ShieldCheck,t.clear,t.clearText],[Warehouse,t.useful,t.usefulText]] as const;return <main className="editorial-page"><section className="editorial-hero"><div className="shell"><p className="kicker">{t.eyebrow}</p><h1>{t.title} <em>{t.accent}</em></h1><p>{t.intro}</p></div></section><section className="story-section"><div className="shell story-grid"><div className="story-index">NOSSA<br/>TERRA<span>01</span></div><div><p className="kicker">{t.reason}</p><h2>{t.reasonTitle}</h2><p>{t.reasonText}</p><blockquote>{t.quote.split("\n").map((line,i)=><span key={line}>{i>0&&<br/>}{line}</span>)}</blockquote></div></div></section><section className="values-section"><div className="shell"><div className="values-head"><p className="kicker">{t.guide}</p><h2>{t.guideTitle}</h2></div><div className="value-grid">{values.map(([Icon,title,description],i)=><article key={title}><Icon/><span>0{i+1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section></main>}
