"use client";

import { CheckCircle2, MessageCircle, Search, Warehouse } from "lucide-react";
import { useLanguage } from "@/components/language-provider";

const text={
  fr:{eyebrow:"Simple et accompagné",title:"Du besoin à la visite,",accent:"en trois étapes.",intro:"AgroStock vous aide à identifier un espace, comprendre ses caractéristiques et organiser une visite accompagnée.",explore:"Explorez",exploreTitle:"Trouvez l’espace adapté.",exploreText:"Recherchez par ville, quartier, nom, propriétaire ou entreprise. Ouvrez une annonce pour consulter sa superficie, ses équipements et sa position sur la carte.",connect:"Demandez une visite",connectTitle:"AgroStock organise la rencontre.",connectText:"Envoyez votre demande depuis la fiche : notre équipe vous accompagne sur place pour la visite et la négociation.",visit:"Vérifiez",visitTitle:"Visitez et concluez sereinement.",visitText:"Utilisez la carte pour vous orienter, visitez le lieu avec notre équipe et vérifiez les conditions avant de conclure.",tip:"Bon réflexe",tipTitle:"Visitez toujours l’espace avant tout engagement.",tipText:"AgroStock accompagne chaque visite et chaque négociation mais ne remplace pas la vérification physique des lieux et des documents."},
  pt:{eyebrow:"Simples e acompanhado",title:"Da necessidade à visita,",accent:"em três etapas.",intro:"A AgroStock ajuda-o a identificar um espaço, compreender as suas características e organizar uma visita acompanhada.",explore:"Explore",exploreTitle:"Encontre o espaço certo.",exploreText:"Pesquise por cidade, bairro, nome, proprietário ou empresa. Abra um anúncio para consultar a área, os equipamentos e a localização no mapa.",connect:"Peça uma visita",connectTitle:"A AgroStock organiza o encontro.",connectText:"Envie o seu pedido a partir da ficha: a nossa equipa acompanha-o no local para a visita e a negociação.",visit:"Verifique",visitTitle:"Visite e conclua com tranquilidade.",visitText:"Use o mapa para se orientar, visite o local com a nossa equipa e confirme as condições antes de decidir.",tip:"Bom reflexo",tipTitle:"Visite sempre o espaço antes de assumir qualquer compromisso.",tipText:"A AgroStock acompanha cada visita e negociação, mas não substitui a verificação física dos locais e documentos."},
  en:{eyebrow:"Simple and guided",title:"From need to visit,",accent:"in three steps.",intro:"AgroStock helps you identify a space, understand its features and arrange a guided visit.",explore:"Explore",exploreTitle:"Find the right space.",exploreText:"Search by city, neighborhood, name, owner or company. Open a listing to see its area, facilities and map location.",connect:"Request a visit",connectTitle:"AgroStock arranges the meeting.",connectText:"Send your request from the listing: our team accompanies you on site for the visit and negotiation.",visit:"Verify",visitTitle:"Visit and close with confidence.",visitText:"Use the map to get oriented, visit the space with our team and check the conditions before deciding.",tip:"Good practice",tipTitle:"Always visit the space before making a commitment.",tipText:"AgroStock accompanies every visit and negotiation but does not replace physical checks of the space and documents."}
} as const;

export default function HowPage(){const{lang}=useLanguage();const t=text[lang];const steps=[[Search,t.explore,t.exploreTitle,t.exploreText],[MessageCircle,t.connect,t.connectTitle,t.connectText],[Warehouse,t.visit,t.visitTitle,t.visitText]] as const;return <main className="editorial-page how-page"><section className="editorial-hero"><div className="shell"><p className="kicker">{t.eyebrow}</p><h1>{t.title} <em>{t.accent}</em></h1><p>{t.intro}</p></div></section><section className="process-section"><div className="shell process-list">{steps.map(([Icon,eyebrow,title,description],i)=><article key={title}><div className="process-number">0{i+1}</div><Icon/><div><p className="kicker">{eyebrow}</p><h2>{title}</h2><p>{description}</p></div></article>)}</div></section><section className="safety-note"><div className="shell"><CheckCircle2/><div><p className="kicker">{t.tip}</p><h2>{t.tipTitle}</h2><p>{t.tipText}</p></div></div></section></main>}
