"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, Building2, CheckCircle2, ChevronDown, Facebook, Instagram, MapPin, MessageCircle, Phone, Search, ShieldCheck, SlidersHorizontal, Warehouse as WarehouseIcon } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useLanguage } from "@/components/language-provider";
import type { Lang } from "@/components/language-provider";
import type { Warehouse } from "@/data/warehouses";

const locations=["Toutes les villes","Bissau","Safim","Bafatá","Gabú","Canchungo"];
const categories=["Tous les types","Entrepôt sec","Hangar","Froid","Magasin","Industriel","Agricole"];
const whatsappPublish="https://wa.me/245957783202?text=Bonjour%2C%20je%20veux%20publier%20un%20warehouse%20sur%20AgroStock";
const copy={
fr:{publish:"Publier un warehouse",badge:"Des espaces vérifiés. Un contact direct.",title1:"Votre espace.",title2:"Au bon endroit.",intro:"Trouvez l’entrepôt, le hangar ou le dépôt adapté à votre activité en Guinée-Bissau.",see:"Voir les annonces",offer:"Je propose un espace",location:"Localisation",kind:"Type d’espace",deal:"Transaction",search:"Rechercher",available:"Espaces disponibles",heading:"Trouvez votre prochain point d’appui.",compare:"Comparez les espaces et échangez directement avec les propriétaires.",placeholder:"Rechercher par ville, quartier...",all:"Tous",rent:"À louer",sale:"À vendre",results:"résultats",call:"Appeler",simple:"Simple et direct",steps:"Un espace en trois étapes.",find:"Cherchez",findText:"Filtrez les annonces selon la ville, le type et votre besoin.",talk:"Échangez",talkText:"Contactez directement le propriétaire par appel ou WhatsApp.",visit:"Visitez",visitText:"Organisez la visite et concluez sans intermédiaire.",owner:"Vous avez un espace disponible ?",ownerTitle:"Votre entrepôt mérite les bons locataires.",ownerText:"Publiez votre annonce et recevez des demandes directes d’entreprises locales.",details:"Voir toutes les informations",about:"À propos de cet espace",equipment:"Équipements et accès",contact:"Propriétaire",map:"Localisation sur la carte"},
pt:{publish:"Publicar um warehouse",badge:"Espaços verificados. Contacto direto.",title1:"O seu espaço.",title2:"No lugar certo.",intro:"Encontre o armazém, hangar ou depósito ideal para a sua atividade na Guiné-Bissau.",see:"Ver anúncios",offer:"Propor um espaço",location:"Localização",kind:"Tipo de espaço",deal:"Negócio",search:"Pesquisar",available:"Espaços disponíveis",heading:"Encontre o seu próximo ponto de apoio.",compare:"Compare os espaços e fale diretamente com os proprietários.",placeholder:"Pesquisar por cidade, bairro...",all:"Todos",rent:"Para alugar",sale:"À venda",results:"resultados",call:"Ligar",simple:"Simples e direto",steps:"Um espaço em três etapas.",find:"Pesquise",findText:"Filtre os anúncios por cidade, tipo e necessidade.",talk:"Converse",talkText:"Contacte o proprietário diretamente por chamada ou WhatsApp.",visit:"Visite",visitText:"Marque a visita e feche o negócio sem intermediários.",owner:"Tem um espaço disponível?",ownerTitle:"O seu armazém merece os clientes certos.",ownerText:"Publique o anúncio e receba pedidos diretos de empresas locais.",details:"Ver todas as informações",about:"Sobre este espaço",equipment:"Equipamentos e acesso",contact:"Proprietário",map:"Localização no mapa"},
en:{publish:"List a warehouse",badge:"Verified spaces. Direct contact.",title1:"Your space.",title2:"In the right place.",intro:"Find the warehouse, hangar or storage space your business needs in Guinea-Bissau.",see:"Browse listings",offer:"List my space",location:"Location",kind:"Space type",deal:"Transaction",search:"Search",available:"Available spaces",heading:"Find your next base of operations.",compare:"Compare spaces and speak directly with owners.",placeholder:"Search by city or neighborhood...",all:"All",rent:"For rent",sale:"For sale",results:"results",call:"Call",simple:"Simple and direct",steps:"A space in three steps.",find:"Search",findText:"Filter listings by city, type and business need.",talk:"Connect",talkText:"Contact the owner directly by phone or WhatsApp.",visit:"Visit",visitText:"Schedule a visit and close without a middleman.",owner:"Have a space available?",ownerTitle:"Your warehouse deserves the right tenants.",ownerText:"List your space and receive direct requests from local businesses.",details:"View all information",about:"About this space",equipment:"Facilities and access",contact:"Owner",map:"Location on the map"}
} as const;

function contactMessage(item:Warehouse,lang:Lang){return encodeURIComponent(lang==="pt"?`Olá, tenho interesse no espaço « ${item.name} » no AgroStock. Ainda está disponível?`:lang==="en"?`Hello, I am interested in “${item.name}” on AgroStock. Is it available?`:`Bonjour, je suis intéressé(e) par « ${item.name} » sur AgroStock. Est-il disponible ?`)}

function ContactActions({item,lang}:{item:Warehouse;lang:Lang}){const tr=copy[lang];return <div className="contact-actions" onClick={e=>e.stopPropagation()}><a className="whatsapp-btn" href={`https://wa.me/${item.phone}?text=${contactMessage(item,lang)}`} target="_blank" rel="noreferrer"><MessageCircle size={19}/>WhatsApp</a><a className="call-btn" href={`tel:+${item.phone}`}><Phone size={19}/>{tr.call}</a></div>}

function Card({item,lang,onOpen}:{item:Warehouse;lang:Lang;onOpen:()=>void}){const tr=copy[lang];return <article className="warehouse-card clickable-card" onClick={onOpen}><div className="card-image"><Image src={item.image} alt={item.name} fill sizes="(max-width:760px) 100vw,(max-width:1100px) 50vw,33vw"/><span className={`deal-tag ${item.type==="Vente"?"sale":""}`}>{item.type==="Location"?tr.rent:tr.sale}</span></div><div className="card-body"><div className="card-topline"><span>{item.category}</span><strong>{item.area} m²</strong></div><h3>{item.name}</h3><p className="place"><MapPin size={16}/>{item.neighborhood}, {item.location}</p><div className="tags">{item.tags.map(tag=><span key={tag}><CheckCircle2 size={13}/>{tag}</span>)}</div><button className="card-details" onClick={onOpen}>{tr.details}<ArrowRight size={15}/></button><ContactActions item={item} lang={lang}/></div></article>}

function WarehouseDialog({item,lang,open,onOpenChange}:{item:Warehouse|null;lang:Lang;open:boolean;onOpenChange:(open:boolean)=>void}){if(!item)return null;const tr=copy[lang],[lat,lng]=item.coordinates;const bbox=`${lng-.025},${lat-.018},${lng+.025},${lat+.018}`;const mapUrl=`https://www.openstreetmap.org/export/embed.html?bbox=${encodeURIComponent(bbox)}&layer=mapnik&marker=${lat},${lng}`;return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="warehouse-dialog"><div className="dialog-visual"><Image src={item.image} alt={item.name} fill sizes="(max-width:700px) 100vw,720px"/><span className={`deal-tag ${item.type==="Vente"?"sale":""}`}>{item.type==="Location"?tr.rent:tr.sale}</span></div><div className="dialog-content"><DialogHeader><p className="dialog-category">{item.category} · {item.area} m²</p><DialogTitle>{item.name}</DialogTitle><DialogDescription><MapPin size={16}/>{item.neighborhood}, {item.location}</DialogDescription></DialogHeader><section><h3>{tr.about}</h3><p>{item.description}</p></section><section><h3>{tr.equipment}</h3><div className="dialog-tags">{item.tags.map(tag=><span key={tag}><CheckCircle2 size={15}/>{tag}</span>)}</div></section><div className="dialog-meta"><div><small>{tr.contact}</small><strong>{item.contactName}</strong></div><div><small>{tr.deal}</small><strong>{item.type==="Location"?tr.rent:tr.sale}</strong></div></div><section className="map-section"><h3>{tr.map}</h3><iframe src={mapUrl} title={`${tr.map} — ${item.name}`} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></section><ContactActions item={item} lang={lang}/></div></DialogContent></Dialog>}

export function WarehouseDirectory({warehouses}:{warehouses:Warehouse[]}){const{lang}=useLanguage();const tr=copy[lang];const[location,setLocation]=useState("Toutes les villes"),[category,setCategory]=useState("Tous les types"),[deal,setDeal]=useState("Tous"),[query,setQuery]=useState(""),[selected,setSelected]=useState<Warehouse|null>(null);const results=useMemo(()=>warehouses.filter(item=>(location==="Toutes les villes"||item.location===location)&&(category==="Tous les types"||item.category===category)&&(deal==="Tous"||item.type===deal)&&(!query.trim()||`${item.name} ${item.location} ${item.neighborhood} ${item.category}`.toLowerCase().includes(query.toLowerCase()))),[warehouses,location,category,deal,query]);const scroll=()=>document.getElementById("annonces")?.scrollIntoView({behavior:"smooth"});return <>
<main id="top"><section className="hero"><div className="hero-photo"><Image src="/warehouse-hero.svg" alt="Entrepôt AgroStock" fill priority sizes="100vw"/></div><div className="hero-overlay"/><div className="shell hero-content"><p className="eyebrow"><ShieldCheck size={17}/>{tr.badge}</p><h1>{tr.title1}<br/><em>{tr.title2}</em></h1><p className="hero-copy">{tr.intro}</p><div className="hero-buttons"><button onClick={scroll}>{tr.see}<ArrowRight size={18}/></button><a href={whatsappPublish} target="_blank" rel="noreferrer">{tr.offer}</a></div><div className="search-box"><label><span><MapPin size={17}/>{tr.location}</span><div><select value={location} onChange={e=>setLocation(e.target.value)}>{locations.map(v=><option key={v}>{v}</option>)}</select><ChevronDown size={16}/></div></label><label><span><WarehouseIcon size={17}/>{tr.kind}</span><div><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(v=><option key={v}>{v}</option>)}</select><ChevronDown size={16}/></div></label><label><span><Building2 size={17}/>{tr.deal}</span><div><select value={deal} onChange={e=>setDeal(e.target.value)}><option value="Tous">{tr.all}</option><option value="Location">{tr.rent}</option><option value="Vente">{tr.sale}</option></select><ChevronDown size={16}/></div></label><button className="search-submit" onClick={scroll}><Search size={19}/>{tr.search}</button></div></div></section>
<section className="listings" id="annonces"><div className="shell"><div className="section-head"><div><p className="kicker">{tr.available}</p><h2>{tr.heading}</h2></div><p>{tr.compare}</p></div><div className="toolbar"><div className="quick-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={tr.placeholder}/></div><div className="deal-tabs"><button className={deal==="Tous"?"active":""} onClick={()=>setDeal("Tous")}>{tr.all}</button><button className={deal==="Location"?"active":""} onClick={()=>setDeal("Location")}>{tr.rent}</button><button className={deal==="Vente"?"active":""} onClick={()=>setDeal("Vente")}>{tr.sale}</button></div><span className="filter-label"><SlidersHorizontal size={17}/>{results.length} {tr.results}</span></div><div className="card-grid">{results.map(item=><Card key={item.id} item={item} lang={lang} onOpen={()=>setSelected(item)}/>)}</div></div></section>
<section className="steps"><div className="shell"><p className="kicker">{tr.simple}</p><h2>{tr.steps}</h2><div className="step-grid"><div><span>01</span><Search/><h3>{tr.find}</h3><p>{tr.findText}</p></div><div><span>02</span><MessageCircle/><h3>{tr.talk}</h3><p>{tr.talkText}</p></div><div><span>03</span><WarehouseIcon/><h3>{tr.visit}</h3><p>{tr.visitText}</p></div></div></div></section><section className="owner-cta"><div className="shell owner-inner"><div><p className="kicker">{tr.owner}</p><h2>{tr.ownerTitle}</h2><p>{tr.ownerText}</p></div><a href={whatsappPublish} target="_blank" rel="noreferrer">{tr.publish}<MessageCircle size={18}/></a></div></section></main>
<footer><div className="shell footer-top"><div><Link className="brand-logo footer-logo" href="/"><Image src="/agrostock-logo-v2.png" alt="AgroStock" width={300} height={100}/></Link><p>L’annuaire des espaces de stockage<br/>en Guinée-Bissau.</p></div><div><strong>AgroStock</strong><Link href="/a-propos">À propos</Link><Link href="/comment-ca-marche">Comment ça marche</Link><a href={whatsappPublish}>{tr.publish}</a></div><div><strong>Social</strong><span className="socials"><a href="#" aria-label="Facebook"><Facebook/></a><a href="#" aria-label="Instagram"><Instagram/></a></span></div></div><div className="shell copyright"><span>© 2026 AgroStock.</span><span>Guiné-Bissau · Guinea-Bissau</span></div></footer><WarehouseDialog item={selected} lang={lang} open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}/></>}
