"use client";

import Image from "next/image";
import { useMemo, useState } from "react";
import { ArrowRight, Building2, CheckCircle2, MapPin, MessageCircle, Navigation, Phone, Search, ShieldCheck, SlidersHorizontal, Warehouse as WarehouseIcon } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useLanguage } from "@/components/language-provider";
import type { Lang } from "@/components/language-provider";
import type { Warehouse } from "@/data/warehouses";

const agroPhone = "245957783202";
const whatsappPublish = `https://wa.me/${agroPhone}?text=Bonjour%2C%20je%20veux%20publier%20un%20warehouse%20sur%20AgroStock`;

const copy={
fr:{publish:"Publier un warehouse",badge:"Des espaces vérifiés. Une visite accompagnée.",title1:"Votre espace.",title2:"Au bon endroit.",intro:"Trouvez et localisez l’entrepôt, le hangar ou le dépôt adapté à votre activité en Guinée-Bissau — disponible ou déjà occupé.",see:"Voir les annonces",offer:"Je propose un espace",search:"Rechercher",available:"Espaces référencés",heading:"Trouvez votre prochain point d’appui.",compare:"Cherchez par nom, quartier, ville, propriétaire ou entreprise.",placeholder:"Nom, quartier, ville, propriétaire, entreprise…",all:"Tous",rent:"À louer",sale:"À vendre",results:"résultats",requestVisit:"Demander une visite",callAgro:"Appeler AgroStock",directions:"Itinéraire",simple:"Simple et accompagné",steps:"Un espace en trois étapes.",find:"Cherchez",findText:"Trouvez et localisez l’espace grâce à la recherche et à la carte.",talk:"Demandez",talkText:"Envoyez une demande de visite : AgroStock prend le relais avec le propriétaire.",visit:"Visitez",visitText:"Notre équipe vous accompagne sur place pour visiter et négocier.",owner:"Vous avez un espace disponible ?",ownerTitle:"Votre entrepôt mérite les bons locataires.",ownerText:"Publiez votre annonce : AgroStock organise les visites et la négociation pour vous.",details:"Voir toutes les informations",about:"À propos de cet espace",equipment:"Équipements et accès",contact:"Propriétaire",map:"Localisation sur la carte",deal:"Transaction",occupied:"Occupé",occupiedBy:"Occupé par"},
pt:{publish:"Publicar um warehouse",badge:"Espaços verificados. Visita acompanhada.",title1:"O seu espaço.",title2:"No lugar certo.",intro:"Encontre e localize o armazém, hangar ou depósito ideal para a sua atividade na Guiné-Bissau — disponível ou já ocupado.",see:"Ver anúncios",offer:"Propor um espaço",search:"Pesquisar",available:"Espaços referenciados",heading:"Encontre o seu próximo ponto de apoio.",compare:"Pesquise por nome, bairro, cidade, proprietário ou empresa.",placeholder:"Nome, bairro, cidade, proprietário, empresa…",all:"Todos",rent:"Para alugar",sale:"À venda",results:"resultados",requestVisit:"Pedir uma visita",callAgro:"Ligar para a AgroStock",directions:"Itinerário",simple:"Simples e acompanhado",steps:"Um espaço em três etapas.",find:"Pesquise",findText:"Encontre e localize o espaço com a pesquisa e o mapa.",talk:"Peça",talkText:"Envie um pedido de visita: a AgroStock trata do contacto com o proprietário.",visit:"Visite",visitText:"A nossa equipa acompanha-o no local para visitar e negociar.",owner:"Tem um espaço disponível?",ownerTitle:"O seu armazém merece os clientes certos.",ownerText:"Publique o anúncio: a AgroStock organiza as visitas e a negociação por si.",details:"Ver todas as informações",about:"Sobre este espaço",equipment:"Equipamentos e acesso",contact:"Proprietário",map:"Localização no mapa",deal:"Negócio",occupied:"Ocupado",occupiedBy:"Ocupado por"},
en:{publish:"List a warehouse",badge:"Verified spaces. A guided visit.",title1:"Your space.",title2:"In the right place.",intro:"Find and locate the warehouse, hangar or storage space your business needs in Guinea-Bissau — available or already occupied.",see:"Browse listings",offer:"List my space",search:"Search",available:"Referenced spaces",heading:"Find your next base of operations.",compare:"Search by name, neighborhood, city, owner or company.",placeholder:"Name, neighborhood, city, owner, company…",all:"All",rent:"For rent",sale:"For sale",results:"results",requestVisit:"Request a visit",callAgro:"Call AgroStock",directions:"Directions",simple:"Simple and guided",steps:"A space in three steps.",find:"Search",findText:"Find and locate the space through search and the map.",talk:"Request",talkText:"Send a visit request: AgroStock takes it from there with the owner.",visit:"Visit",visitText:"Our team accompanies you on site to visit and negotiate.",owner:"Have a space available?",ownerTitle:"Your warehouse deserves the right tenants.",ownerText:"List your space: AgroStock organizes the visits and negotiation for you.",details:"View all information",about:"About this space",equipment:"Facilities and access",contact:"Owner",map:"Location on the map",deal:"Transaction",occupied:"Occupied",occupiedBy:"Occupied by"}
} as const;

function visitMessage(item:Warehouse,lang:Lang){return encodeURIComponent(lang==="pt"?`Olá, quero pedir uma visita ao espaço « ${item.name} » no AgroStock. Podem organizar?`:lang==="en"?`Hello, I would like to request a visit for “${item.name}” on AgroStock. Can you arrange it?`:`Bonjour, je souhaite demander une visite pour « ${item.name} » sur AgroStock. Pouvez-vous l’organiser ?`)}

function directionsUrl(item:Warehouse){const[lat,lng]=item.coordinates;return `https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}`}

function DirectionsButton({item,lang}:{item:Warehouse;lang:Lang}){const tr=copy[lang];return <a className="directions-btn" href={directionsUrl(item)} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}><Navigation size={17}/>{tr.directions}</a>}

function ContactActions({item,lang}:{item:Warehouse;lang:Lang}){const tr=copy[lang];return <div className="contact-actions" onClick={e=>e.stopPropagation()}><a className="whatsapp-btn" href={`https://wa.me/${agroPhone}?text=${visitMessage(item,lang)}`} target="_blank" rel="noreferrer"><MessageCircle size={19}/>{tr.requestVisit}</a><a className="call-btn" href={`tel:+${agroPhone}`}><Phone size={19}/>{tr.callAgro}</a></div>}

function OccupiedNote({item,lang}:{item:Warehouse;lang:Lang}){const tr=copy[lang];return <p className="occupied-note" onClick={e=>e.stopPropagation()}><Building2 size={15}/>{tr.occupiedBy} {item.companies?.join(", ")}</p>}

function Card({item,lang,onOpen}:{item:Warehouse;lang:Lang;onOpen:()=>void}){const tr=copy[lang];const occupied=item.status==="occupee";return <article className="warehouse-card clickable-card" onClick={onOpen}><div className="card-image"><Image src={item.image} alt={item.name} fill sizes="(max-width:760px) 100vw,(max-width:1100px) 50vw,33vw"/><span className={`deal-tag ${occupied?"occupied":item.type==="Vente"?"sale":""}`}>{occupied?tr.occupied:item.type==="Location"?tr.rent:tr.sale}</span></div><div className="card-body"><div className="card-topline"><span>{item.category}</span><strong>{item.area} m²</strong></div><h3>{item.name}</h3><p className="place"><MapPin size={16}/>{item.neighborhood}, {item.location}</p><div className="tags">{item.tags.map(tag=><span key={tag}><CheckCircle2 size={13}/>{tag}</span>)}</div><button className="card-details" onClick={onOpen}>{tr.details}<ArrowRight size={15}/></button>{occupied?<OccupiedNote item={item} lang={lang}/>:<ContactActions item={item} lang={lang}/>}<DirectionsButton item={item} lang={lang}/></div></article>}

function WarehouseDialog({item,lang,open,onOpenChange}:{item:Warehouse|null;lang:Lang;open:boolean;onOpenChange:(open:boolean)=>void}){if(!item)return null;const tr=copy[lang],[lat,lng]=item.coordinates,occupied=item.status==="occupee";const bbox=`${lng-.025},${lat-.018},${lng+.025},${lat+.018}`;const mapUrl=`https://www.openstreetmap.org/export/embed.html?bbox=${encodeURIComponent(bbox)}&layer=mapnik&marker=${lat},${lng}`;return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="warehouse-dialog"><div className="dialog-visual"><Image src={item.image} alt={item.name} fill sizes="(max-width:700px) 100vw,720px"/><span className={`deal-tag ${occupied?"occupied":item.type==="Vente"?"sale":""}`}>{occupied?tr.occupied:item.type==="Location"?tr.rent:tr.sale}</span></div><div className="dialog-content"><DialogHeader><p className="dialog-category">{item.category} · {item.area} m²</p><DialogTitle>{item.name}</DialogTitle><DialogDescription><MapPin size={16}/>{item.neighborhood}, {item.location}</DialogDescription></DialogHeader><section><h3>{tr.about}</h3><p>{item.description}</p></section><section><h3>{tr.equipment}</h3><div className="dialog-tags">{item.tags.map(tag=><span key={tag}><CheckCircle2 size={15}/>{tag}</span>)}</div></section><div className="dialog-meta"><div><small>{tr.contact}</small><strong>{item.owner}</strong></div><div><small>{tr.deal}</small><strong>{occupied?tr.occupied:item.type==="Location"?tr.rent:tr.sale}</strong></div></div><section className="map-section"><h3>{tr.map}</h3><iframe src={mapUrl} title={`${tr.map} — ${item.name}`} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><DirectionsButton item={item} lang={lang}/></section>{occupied?<OccupiedNote item={item} lang={lang}/>:<ContactActions item={item} lang={lang}/>}</div></DialogContent></Dialog>}

export function WarehouseDirectory({warehouses}:{warehouses:Warehouse[]}){const{lang}=useLanguage();const tr=copy[lang];const[deal,setDeal]=useState("Tous"),[query,setQuery]=useState(""),[selected,setSelected]=useState<Warehouse|null>(null);const results=useMemo(()=>warehouses.filter(item=>{if(deal!=="Tous"&&!(item.status==="disponible"&&item.type===deal))return false;if(!query.trim())return true;const haystack=`${item.name} ${item.location} ${item.neighborhood} ${item.owner} ${(item.companies||[]).join(" ")}`.toLowerCase();return haystack.includes(query.trim().toLowerCase())}),[warehouses,deal,query]);const scroll=()=>document.getElementById("annonces")?.scrollIntoView({behavior:"smooth"});return <>
<main id="top"><section className="hero"><div className="hero-photo"><Image src="/warehouse-hero.svg" alt="Entrepôt AgroStock" fill priority sizes="100vw"/></div><div className="hero-overlay"/><div className="shell hero-content"><p className="eyebrow"><ShieldCheck size={17}/>{tr.badge}</p><h1>{tr.title1}<br/><em>{tr.title2}</em></h1><p className="hero-copy">{tr.intro}</p><div className="hero-buttons"><button onClick={scroll}>{tr.see}<ArrowRight size={18}/></button><a href={whatsappPublish} target="_blank" rel="noreferrer">{tr.offer}</a></div></div></section>
<section className="listings" id="annonces"><div className="shell"><div className="section-head"><div><p className="kicker">{tr.available}</p><h2>{tr.heading}</h2></div><p>{tr.compare}</p></div><div className="toolbar"><label className="quick-search" aria-label={tr.search}><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={tr.placeholder}/></label><div className="deal-tabs"><button className={deal==="Tous"?"active":""} onClick={()=>setDeal("Tous")}>{tr.all}</button><button className={deal==="Location"?"active":""} onClick={()=>setDeal("Location")}>{tr.rent}</button><button className={deal==="Vente"?"active":""} onClick={()=>setDeal("Vente")}>{tr.sale}</button></div><span className="filter-label"><SlidersHorizontal size={17}/>{results.length} {tr.results}</span></div><div className="card-grid">{results.map(item=><Card key={item.id} item={item} lang={lang} onOpen={()=>setSelected(item)}/>)}</div></div></section>
<section className="steps"><div className="shell"><p className="kicker">{tr.simple}</p><h2>{tr.steps}</h2><div className="step-grid"><div><span>01</span><Search/><h3>{tr.find}</h3><p>{tr.findText}</p></div><div><span>02</span><MessageCircle/><h3>{tr.talk}</h3><p>{tr.talkText}</p></div><div><span>03</span><WarehouseIcon/><h3>{tr.visit}</h3><p>{tr.visitText}</p></div></div></div></section><section className="owner-cta"><div className="shell owner-inner"><div><p className="kicker">{tr.owner}</p><h2>{tr.ownerTitle}</h2><p>{tr.ownerText}</p></div><a href={whatsappPublish} target="_blank" rel="noreferrer">{tr.publish}<MessageCircle size={18}/></a></div></section></main>
<WarehouseDialog item={selected} lang={lang} open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}/></>}
